export type ShoeCategory = "race" | "tempo" | "easy" | "all-around";

export interface Shoe {
  id: string;
  brand: string;
  model: string;
  category: ShoeCategory;
  weight: number; // grams
  cushioning: number; // 1–10
  rebound: number; // 1–10
  stability: number; // 1–10
  carbonPlate: boolean;
  price: number; // EUR
  colors: string[];
  releaseYear: number;
}

export const shoes: Shoe[] = [
  // ─── ADIDAS ──────────────────────────────────────────────────────────────────
  {
    id: "adidas-evo-sl",
    brand: "Adidas",
    model: "Adizero Evo SL",
    category: "tempo",
    weight: 218,
    cushioning: 7,
    rebound: 9,
    stability: 6,
    carbonPlate: false,
    price: 150,
    colors: ["#00AA44", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "adidas-sl2",
    brand: "Adidas",
    model: "Adizero SL 2",
    category: "all-around",
    weight: 258,
    cushioning: 7,
    rebound: 7,
    stability: 7,
    carbonPlate: false,
    price: 120,
    colors: ["#1C1C1E", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "adidas-boston-13",
    brand: "Adidas",
    model: "Adizero Boston 13",
    category: "tempo",
    weight: 243,
    cushioning: 8,
    rebound: 8,
    stability: 7,
    carbonPlate: false,
    price: 160,
    colors: ["#0044CC", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "adidas-adios-9",
    brand: "Adidas",
    model: "Adizero Adios 9",
    category: "race",
    weight: 205,
    cushioning: 7,
    rebound: 9,
    stability: 6,
    carbonPlate: false,
    price: 170,
    colors: ["#FF6600", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "adidas-adios-pro-4",
    brand: "Adidas",
    model: "Adizero Adios Pro 4",
    category: "race",
    weight: 220,
    cushioning: 8,
    rebound: 10,
    stability: 6,
    carbonPlate: true,
    price: 260,
    colors: ["#00AA44", "#FFD700"],
    releaseYear: 2024,
  },
  {
    id: "adidas-adios-pro-evo-2",
    brand: "Adidas",
    model: "Adizero Adios Pro Evo 2",
    category: "race",
    weight: 139,
    cushioning: 6,
    rebound: 10,
    stability: 5,
    carbonPlate: true,
    price: 500,
    colors: ["#FFFFFF", "#00AA44"],
    releaseYear: 2024,
  },
  {
    id: "adidas-adistar-byd",
    brand: "Adidas",
    model: "Adistar BYD",
    category: "easy",
    weight: 310,
    cushioning: 10,
    rebound: 6,
    stability: 9,
    carbonPlate: false,
    price: 165,
    colors: ["#3A3A5C", "#FFFFFF"],
    releaseYear: 2024,
  },

  // ─── NIKE ────────────────────────────────────────────────────────────────────
  {
    id: "nike-pegasus-42",
    brand: "Nike",
    model: "Pegasus 42",
    category: "all-around",
    weight: 280,
    cushioning: 7,
    rebound: 7,
    stability: 7,
    carbonPlate: false,
    price: 135,
    colors: ["#1C1C1E", "#FFFFFF"],
    releaseYear: 2025,
  },
  {
    id: "nike-pegasus-plus",
    brand: "Nike",
    model: "Pegasus Plus",
    category: "tempo",
    weight: 248,
    cushioning: 8,
    rebound: 8,
    stability: 7,
    carbonPlate: false,
    price: 165,
    colors: ["#FF4500", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "nike-pegasus-premium",
    brand: "Nike",
    model: "Pegasus Premium",
    category: "easy",
    weight: 295,
    cushioning: 9,
    rebound: 8,
    stability: 7,
    carbonPlate: false,
    price: 200,
    colors: ["#7B68EE", "#FFFFFF"],
    releaseYear: 2025,
  },
  {
    id: "nike-vomero-18",
    brand: "Nike",
    model: "Vomero 18",
    category: "easy",
    weight: 315,
    cushioning: 10,
    rebound: 6,
    stability: 8,
    carbonPlate: false,
    price: 185,
    colors: ["#4A90D9", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "nike-vomero-plus",
    brand: "Nike",
    model: "Vomero Plus",
    category: "easy",
    weight: 320,
    cushioning: 10,
    rebound: 7,
    stability: 8,
    carbonPlate: false,
    price: 210,
    colors: ["#6EE7B7", "#1C1C1E"],
    releaseYear: 2025,
  },
  {
    id: "nike-structure-plus",
    brand: "Nike",
    model: "Structure Plus",
    category: "all-around",
    weight: 300,
    cushioning: 8,
    rebound: 6,
    stability: 10,
    carbonPlate: false,
    price: 140,
    colors: ["#2255AA", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "nike-zoom-fly-6",
    brand: "Nike",
    model: "Zoom Fly 6",
    category: "tempo",
    weight: 250,
    cushioning: 8,
    rebound: 9,
    stability: 7,
    carbonPlate: true,
    price: 185,
    colors: ["#00C8FF", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "nike-vaporfly-4",
    brand: "Nike",
    model: "Vaporfly 4",
    category: "race",
    weight: 192,
    cushioning: 7,
    rebound: 10,
    stability: 6,
    carbonPlate: true,
    price: 250,
    colors: ["#FF9900", "#FFFFFF"],
    releaseYear: 2025,
  },
  {
    id: "nike-streakfly-2",
    brand: "Nike",
    model: "Streakfly 2",
    category: "race",
    weight: 172,
    cushioning: 5,
    rebound: 9,
    stability: 5,
    carbonPlate: false,
    price: 160,
    colors: ["#FF0044", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "nike-alphafly-3",
    brand: "Nike",
    model: "Alphafly 3",
    category: "race",
    weight: 225,
    cushioning: 9,
    rebound: 10,
    stability: 6,
    carbonPlate: true,
    price: 285,
    colors: ["#FF4500", "#FFFFFF"],
    releaseYear: 2024,
  },

  // ─── ASICS ───────────────────────────────────────────────────────────────────
  {
    id: "asics-superblast-3",
    brand: "ASICS",
    model: "Superblast 3",
    category: "easy",
    weight: 255,
    cushioning: 9,
    rebound: 9,
    stability: 6,
    carbonPlate: false,
    price: 200,
    colors: ["#FF6600", "#FFFFFF"],
    releaseYear: 2025,
  },
  {
    id: "asics-novablast-5",
    brand: "ASICS",
    model: "Novablast 5",
    category: "all-around",
    weight: 265,
    cushioning: 8,
    rebound: 9,
    stability: 6,
    carbonPlate: false,
    price: 160,
    colors: ["#00BFFF", "#FFFFFF"],
    releaseYear: 2025,
  },
  {
    id: "asics-nimbus-27",
    brand: "ASICS",
    model: "Gel-Nimbus 27",
    category: "easy",
    weight: 298,
    cushioning: 10,
    rebound: 6,
    stability: 8,
    carbonPlate: false,
    price: 185,
    colors: ["#4A90D9", "#FFFFFF"],
    releaseYear: 2025,
  },
  {
    id: "asics-cumulus-27",
    brand: "ASICS",
    model: "Gel-Cumulus 27",
    category: "all-around",
    weight: 278,
    cushioning: 8,
    rebound: 7,
    stability: 7,
    carbonPlate: false,
    price: 150,
    colors: ["#9966CC", "#FFFFFF"],
    releaseYear: 2025,
  },
  {
    id: "asics-magic-speed-4",
    brand: "ASICS",
    model: "Magic Speed 4",
    category: "tempo",
    weight: 218,
    cushioning: 7,
    rebound: 9,
    stability: 7,
    carbonPlate: true,
    price: 190,
    colors: ["#001A6E", "#FFFFFF"],
    releaseYear: 2025,
  },
  {
    id: "asics-metaspeed-sky-tokyo",
    brand: "ASICS",
    model: "Metaspeed Sky Tokyo",
    category: "race",
    weight: 215,
    cushioning: 7,
    rebound: 10,
    stability: 6,
    carbonPlate: true,
    price: 310,
    colors: ["#FF6600", "#001A6E"],
    releaseYear: 2024,
  },
  {
    id: "asics-metaspeed-edge-tokyo",
    brand: "ASICS",
    model: "Metaspeed Edge Tokyo",
    category: "race",
    weight: 200,
    cushioning: 6,
    rebound: 10,
    stability: 6,
    carbonPlate: true,
    price: 310,
    colors: ["#001A6E", "#FFD700"],
    releaseYear: 2024,
  },
  {
    id: "asics-sonicblast",
    brand: "ASICS",
    model: "Sonicblast",
    category: "race",
    weight: 180,
    cushioning: 5,
    rebound: 9,
    stability: 5,
    carbonPlate: false,
    price: 140,
    colors: ["#FF0044", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "asics-versablast-4",
    brand: "ASICS",
    model: "Versablast 4",
    category: "all-around",
    weight: 255,
    cushioning: 7,
    rebound: 7,
    stability: 7,
    carbonPlate: false,
    price: 110,
    colors: ["#33BBAA", "#FFFFFF"],
    releaseYear: 2025,
  },
  {
    id: "asics-gt1000-14",
    brand: "ASICS",
    model: "GT-1000 14",
    category: "all-around",
    weight: 285,
    cushioning: 7,
    rebound: 6,
    stability: 9,
    carbonPlate: false,
    price: 110,
    colors: ["#2255AA", "#FFFFFF"],
    releaseYear: 2025,
  },
  {
    id: "asics-gt2000-13",
    brand: "ASICS",
    model: "GT-2000 13",
    category: "all-around",
    weight: 275,
    cushioning: 8,
    rebound: 6,
    stability: 10,
    carbonPlate: false,
    price: 140,
    colors: ["#336699", "#FFFFFF"],
    releaseYear: 2025,
  },
  {
    id: "asics-kayano-31",
    brand: "ASICS",
    model: "Kayano 31",
    category: "easy",
    weight: 312,
    cushioning: 10,
    rebound: 6,
    stability: 10,
    carbonPlate: false,
    price: 175,
    colors: ["#2E4057", "#FFFFFF"],
    releaseYear: 2024,
  },
];

export const brands = [...new Set(shoes.map((s) => s.brand))];
export const categories: ShoeCategory[] = ["race", "tempo", "easy", "all-around"];
