export type ShoeCategory = "race" | "tempo" | "easy" | "all-around";

export interface Shoe {
  id: string;
  brand: string;
  model: string;
  category: ShoeCategory;
  weight: number; // grams
  cushioning: number; // 1-10
  rebound: number; // 1-10
  stability: number; // 1-10
  carbonPlate: boolean;
  price: number; // EUR
  colors: string[];
  releaseYear: number;
}

export const shoes: Shoe[] = [
  // NIKE
  {
    id: "nike-alphafly-3",
    brand: "Nike",
    model: "Alphafly 3",
    category: "race",
    weight: 225,
    cushioning: 9,
    rebound: 10,
    stability: 6,
    carbonPlate: true,
    price: 285,
    colors: ["#FF4500", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "nike-vaporfly-3",
    brand: "Nike",
    model: "Vaporfly 3",
    category: "tempo",
    weight: 194,
    cushioning: 7,
    rebound: 9,
    stability: 6,
    carbonPlate: true,
    price: 235,
    colors: ["#00C8FF", "#FFFFFF"],
    releaseYear: 2023,
  },
  {
    id: "nike-invincible-3",
    brand: "Nike",
    model: "Invincible 3",
    category: "easy",
    weight: 320,
    cushioning: 10,
    rebound: 7,
    stability: 7,
    carbonPlate: false,
    price: 185,
    colors: ["#7B68EE", "#FFFFFF"],
    releaseYear: 2023,
  },
  {
    id: "nike-pegasus-41",
    brand: "Nike",
    model: "Pegasus 41",
    category: "all-around",
    weight: 283,
    cushioning: 7,
    rebound: 7,
    stability: 7,
    carbonPlate: false,
    price: 135,
    colors: ["#1C1C1E", "#FFFFFF"],
    releaseYear: 2024,
  },

  // ADIDAS
  {
    id: "adidas-adizero-adios-pro-3",
    brand: "Adidas",
    model: "Adizero Adios Pro 3",
    category: "race",
    weight: 215,
    cushioning: 8,
    rebound: 10,
    stability: 6,
    carbonPlate: true,
    price: 250,
    colors: ["#00AA44", "#FFFFFF"],
    releaseYear: 2023,
  },
  {
    id: "adidas-adizero-boston-12",
    brand: "Adidas",
    model: "Adizero Boston 12",
    category: "tempo",
    weight: 248,
    cushioning: 8,
    rebound: 8,
    stability: 7,
    carbonPlate: false,
    price: 160,
    colors: ["#0044CC", "#FFFFFF"],
    releaseYear: 2023,
  },
  {
    id: "adidas-ultraboost-light",
    brand: "Adidas",
    model: "Ultraboost Light",
    category: "easy",
    weight: 310,
    cushioning: 9,
    rebound: 7,
    stability: 7,
    carbonPlate: false,
    price: 190,
    colors: ["#1C1C1E", "#FFFFFF"],
    releaseYear: 2023,
  },
  {
    id: "adidas-supernova-rise",
    brand: "Adidas",
    model: "Supernova Rise",
    category: "all-around",
    weight: 290,
    cushioning: 7,
    rebound: 7,
    stability: 7,
    carbonPlate: false,
    price: 125,
    colors: ["#CC4400", "#FFFFFF"],
    releaseYear: 2024,
  },

  // ASICS
  {
    id: "asics-metaspeed-sky-paris",
    brand: "ASICS",
    model: "Metaspeed Sky Paris",
    category: "race",
    weight: 215,
    cushioning: 7,
    rebound: 10,
    stability: 6,
    carbonPlate: true,
    price: 290,
    colors: ["#FF6600", "#001A6E"],
    releaseYear: 2024,
  },
  {
    id: "asics-magic-speed-3",
    brand: "ASICS",
    model: "Magic Speed 3",
    category: "tempo",
    weight: 220,
    cushioning: 7,
    rebound: 8,
    stability: 7,
    carbonPlate: true,
    price: 180,
    colors: ["#001A6E", "#FFFFFF"],
    releaseYear: 2023,
  },
  {
    id: "asics-gel-nimbus-26",
    brand: "ASICS",
    model: "Gel-Nimbus 26",
    category: "easy",
    weight: 300,
    cushioning: 10,
    rebound: 6,
    stability: 8,
    carbonPlate: false,
    price: 175,
    colors: ["#4A90D9", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "asics-gel-kayano-31",
    brand: "ASICS",
    model: "Gel-Kayano 31",
    category: "all-around",
    weight: 310,
    cushioning: 9,
    rebound: 6,
    stability: 10,
    carbonPlate: false,
    price: 165,
    colors: ["#2E4057", "#FFFFFF"],
    releaseYear: 2024,
  },

  // HOKA
  {
    id: "hoka-rocket-x-2",
    brand: "HOKA",
    model: "Rocket X 2",
    category: "race",
    weight: 220,
    cushioning: 8,
    rebound: 9,
    stability: 6,
    carbonPlate: true,
    price: 230,
    colors: ["#FF5500", "#FFFFFF"],
    releaseYear: 2023,
  },
  {
    id: "hoka-mach-6",
    brand: "HOKA",
    model: "Mach 6",
    category: "tempo",
    weight: 252,
    cushioning: 8,
    rebound: 8,
    stability: 6,
    carbonPlate: false,
    price: 155,
    colors: ["#00B4D8", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "hoka-clifton-9",
    brand: "HOKA",
    model: "Clifton 9",
    category: "easy",
    weight: 265,
    cushioning: 10,
    rebound: 6,
    stability: 7,
    carbonPlate: false,
    price: 150,
    colors: ["#6EE7B7", "#FFFFFF"],
    releaseYear: 2023,
  },
  {
    id: "hoka-bondi-8",
    brand: "HOKA",
    model: "Bondi 8",
    category: "all-around",
    weight: 298,
    cushioning: 10,
    rebound: 6,
    stability: 8,
    carbonPlate: false,
    price: 170,
    colors: ["#1C1C1E", "#FFFFFF"],
    releaseYear: 2022,
  },

  // BROOKS
  {
    id: "brooks-hyperion-elite-4",
    brand: "Brooks",
    model: "Hyperion Elite 4",
    category: "race",
    weight: 208,
    cushioning: 7,
    rebound: 10,
    stability: 6,
    carbonPlate: true,
    price: 250,
    colors: ["#FF0055", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "brooks-hyperion-tempo",
    brand: "Brooks",
    model: "Hyperion Tempo",
    category: "tempo",
    weight: 230,
    cushioning: 6,
    rebound: 9,
    stability: 6,
    carbonPlate: false,
    price: 150,
    colors: ["#CC00FF", "#FFFFFF"],
    releaseYear: 2023,
  },
  {
    id: "brooks-ghost-16",
    brand: "Brooks",
    model: "Ghost 16",
    category: "easy",
    weight: 295,
    cushioning: 9,
    rebound: 6,
    stability: 8,
    carbonPlate: false,
    price: 140,
    colors: ["#5566AA", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "brooks-adrenaline-gts-24",
    brand: "Brooks",
    model: "Adrenaline GTS 24",
    category: "all-around",
    weight: 299,
    cushioning: 8,
    rebound: 6,
    stability: 10,
    carbonPlate: false,
    price: 145,
    colors: ["#2255AA", "#FFFFFF"],
    releaseYear: 2024,
  },

  // NEW BALANCE
  {
    id: "nb-fuelcell-supercomp-elite-v4",
    brand: "New Balance",
    model: "FuelCell SuperComp Elite v4",
    category: "race",
    weight: 210,
    cushioning: 8,
    rebound: 10,
    stability: 6,
    carbonPlate: true,
    price: 265,
    colors: ["#FFFFFF", "#FF2200"],
    releaseYear: 2024,
  },
  {
    id: "nb-fuelcell-rebel-v4",
    brand: "New Balance",
    model: "FuelCell Rebel v4",
    category: "tempo",
    weight: 215,
    cushioning: 7,
    rebound: 9,
    stability: 6,
    carbonPlate: false,
    price: 160,
    colors: ["#FF6633", "#FFFFFF"],
    releaseYear: 2024,
  },
  {
    id: "nb-fresh-foam-1080v13",
    brand: "New Balance",
    model: "Fresh Foam X 1080 v13",
    category: "easy",
    weight: 298,
    cushioning: 10,
    rebound: 7,
    stability: 7,
    carbonPlate: false,
    price: 175,
    colors: ["#AA33FF", "#FFFFFF"],
    releaseYear: 2023,
  },
  {
    id: "nb-fresh-foam-860v14",
    brand: "New Balance",
    model: "Fresh Foam X 860 v14",
    category: "all-around",
    weight: 298,
    cushioning: 8,
    rebound: 6,
    stability: 9,
    carbonPlate: false,
    price: 155,
    colors: ["#336699", "#FFFFFF"],
    releaseYear: 2024,
  },
];

export const brands = [...new Set(shoes.map((s) => s.brand))];
export const categories: ShoeCategory[] = ["race", "tempo", "easy", "all-around"];
